service: serverless-translate
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, "qa"}
  environment: ${file(./src/config/env.${self:provider.stage}.json)}
  region: ${self:provider.environment.Region}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - translate:TranslateText
          Resource: "*"
        - Effect: Allow
          Action:
            - comprehend:DetectDominantLanguage
          Resource: "*"

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - "!./src/tests"
    - "!./.husky/"
    - "!./babel.config.js"
    - "!./commitlink.config.js"
    - "!./jest.config.js"
    - "!node_modules/.prisma/client/libquery_engine-*"
    - "node_modules/.prisma/client/libquery_engine-rhel-*"
    - "!node_modules/prisma/libquery_engine-*"
    - "!node_modules/@prisma/engines/**"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  translate:
    handler: src/translate/handler.post
    events:
      - http:
          path: /
          method: post
          cors: true
